homeassistant:
  # Name of the location where Home Assistant is running
  name: Meerzand
  # Location required to calculate the time the sun rises and sets
  latitude: 51.4432618
  longitude: 5.4087704
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 73
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
     script.voordeur_open:
       hidden: True 
     script.deurbel:
       hidden: True
     switch.deurbel:
       icon: mdi:bell-ring
       assumed_state: false
     device_tracker.rtac68u8110:
       friendly_name: ASUS RT AC-68U
       icon: mdi:router-wireless
     device_tracker.nexuswoonkamer:
       icon: mdi:tablet-android
     device_tracker.printerlan:
       icon: mdi:printer
     device_tracker.fritzbox:
       friendly_name: Fritzbox!
       icon: mdi:router-wireless
     device_tracker.amazon5512fadf:
       friendly_name: Alexa
     sensor.pws_temp_c:
       friendly_name: Buitentemperatuur
     sensor.pws_wind_dir:
       friendly_name: Windrichting
     sensor.pws_wind_kph:
       friendly_name: Windsnelheid
     sensor.pws_alerts:
       friendly_name: Alerts
     sensor.pws_observation_time:
       friendly_name: Laatste meting
     sensor.pws_precip_1hr_metric:
       friendly_name: Regen (1 uur)
     sensor.pws_precip_today_metric:
       friendly_name: Regen vandaag
     sensor.pws_visibility_km:
       friendly_name: Zicht (km)
     sensor.br_ground_temperature:
       friendly_name: Grond Temperatuur
     media_player.49pus750212:
       friendly_name: TV
     sensor.br_humidity:
       friendly_name: Humidity
     sensor.br_irradiance:
       friendly_name: Irradiance
     sensor.br_pressure:
       friendly_name: Pressure
     sensor.br_stationname:
       friendly_name: Station Name
     sensor.br_symbol:
       friendly_name: Symbol
     sensor.br_temperature:
       friendly_name: Air Temperature
     sensor.br_wind_direction:
       friendly_name: Wind Direction
     sensor.br_wind_gust:
       friendly_name: Wind Gust
     sensor.br_wind_speed:
       friendly_name: Wind Speed
     
logger:
   default: error
   logs:
     homeassistant.components.rfxtrx: debug
    
remote:
  - platform: harmony
    name: Tim's hub
    host: 192.168.178.24
     
group:
  network:
    name: Network
    entities:
      - device_tracker.rtac68u8110
      - device_tracker.nexuswoonkamer
      - device_tracker.printerlan
      - device_tracker.fritzbox
      - device_tracker.googlehome
      - device_tracker.amazon5512fad5f
      - device_tracker.switch1
      - device_tracker.switch2
      - device_tracker.harmonyhub
      - device_tracker.roamer
      - device_tracker.storer

  woonkamer:
    name: Woonkamer
    entities:
      - media_player.woonkamer
      - sensor.cresta_woonkamer_temperature

  clock:
    name: Date and Time
    entities:
      - sensor.date__time

  Wunderground:
    name: Weather Underground
    entities:
     - sensor.pws_location
     - sun.sun
     - sensor.yr_symbol
     - sensor.pws_alerts
     - sensor.pws_observation_time
     - sensor.pws_precip_1hr_metric
     - sensor.pws_precip_today_metric
     - sensor.pws_temp_c
     - sensor.pws_visibility_km
     - sensor.pws_wind_dir
     - sensor.pws_wind_kph
  buienradar:
    name: Buienradar
    entities:
     - sensor.br_stationname
     - sensor.br_symbol
     - sensor.br_temperature
     - sensor.br_ground_temperature
     - sensor.br_humidity
     - sensor.br_irradiance
     - sensor.br_precipation
     - sensor.br_pressure
     - sensor.br_visibility
     - sensor.br_wind_direction
     - sensor.br_wind_direction_azimuth
     - sensor.br_wind_force
     - sensor.br_wind_gust
     
     
   

frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: /etc/letsencrypt/live/holder.timt.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/holder.timt.org/privkey.pem

# Checks for available updates
updater:

# Enable configuration panel
config:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#customization

# turn on local mqtt broker
#mqtt:
#  broker: localhost
#  port: 1883
#  client_id: homeassistant1
#  keepalive: 60
#  protocol: 3.1


# Location/geofencing etc.
device_tracker:
   - platform: fritz
     username: admin
     password: !secret adminpasswd
     host: 192.168.178.1
   - platform: nmap_tracker
     hosts: 192.168.178.0/24

     
rfxtrx:
  device: /dev/ttyUSB0
  debug: True

cover:
  platform: rfxtrx
  automatic_add: False
  devices:
    071a03000d080601: 
      name: Raam achter
    071a03000d080602:
      name: Raam zijkant
    071a03000d080603:
      name: Raam Links voor
    071a03000d080604:
      name: Raam Midden voor
    071a03000d080609:
      name: Raam Rechts voor

media_player:
  - platform: cast

light:
  - platform: rfxtrx
    automatic_add: True

switch:
  - platform: rfxtrx
    automatic_add: False 
    devices:
      0b110001014206060a010f50:
        name: Voordeur
      0b110002019ac87e01040f50:
        name: Deurbel
        fire_event: True

#  - platform: mqtt
#    name: Lamp 1
#    command_topic: "cmnd/lamp1/power"
#    state_topic: "stat/lamp1/+"
    

 

sensor:
# Weather prediction
  - platform: yr
# Time and date
  - platform: time_date
    display_options:
      - date_time
  - platform: rfxtrx
    automatic_add: True
    devices:
      0a5207013b0e00d02d0169:
        name: Cresta woonkamer

  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - station_id
      - alerts
      - observation_time
      - precip_1hr_metric
      - precip_today_metric
      - temp_c
      - visibility_km
      - wind_dir
      - wind_kph

  - platform: buienradar
    monitored_conditions:
      - stationname
      - symbol
      - humidity
      - temperature
      - groundtemperature
      - windspeed
      - windforce
      - winddirection
      - windazimuth
      - pressure
      - visibility
      - windgust
      - precipitation
      - irradiance
# Living room camera
camera:
  - platform: foscam
    ip: 192.168.178.57
    port: 88
    username: timt
    password: !secret camera_password

notify:
  - platform: pushbullet
    name: Tim
    api_key: !secret pushbullet_key


influxdb:
  host: 127.0.0.1

wemo:
  static:
    - 192.168.178.42

automation:
  - alias: 'warn when door opens'
    initial_state: True
    hide_entity: True
    trigger: 
      platform: state
      entity_id: switch.voordeur
      from: 'off'
      to: 'on'
    action: 
      service: notify.Tim
      data:
        message: "Door open"
        title: "Door open"
  - alias: "voordeur nog open"
    hide_entity: True
    trigger:
      platform: state
      entity_id: switch.voordeur
      from: 'off'
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.voordeur_open
  - alias: 'voordeur dicht'
    hide_entity: True
    trigger:
      platform: state
      entity_id: switch.voordeur
      from: 'on'
      to: 'off'
    action: 
      service: homeassistant.turn_off
      entity_id: script.voordeur_open
  - alias: 'deurbel gaat'
    hide_entity: True
    trigger:
      platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
    action:
       service: homeassistant.turn_on
       entity_id: script.deurbel

script: !include scripts.yaml

