homeassistant:
  # Name of the location where Home Assistant is running
  name: Meerzand
  # Location required to calculate the time the sun rises and sets
  latitude: 51.4432618
  longitude: 5.4087704
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 73
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
     script.voordeur_open:
       hidden: True
     script.deurbel:
       hidden: True
     switch.deurbel:
       icon: mdi:bell-ring
       assumed_state: false
     switch.voordeur:
       icon: mdi:door
       assumed_state: false
     device_tracker.rtac68u8110:
       friendly_name: ASUS RT AC-68U
       icon: mdi:router-wireless
     device_tracker.nexuswoonkamer:
       icon: mdi:tablet-android
     device_tracker.printerlan:
       icon: mdi:printer
     device_tracker.fritzbox:
       friendly_name: Fritzbox!
       icon: mdi:router-wireless
     device_tracker.amazon5512fadf:
       friendly_name: Alexa
     group.all_covers:
       hidden: false
     group.all_switches:
       hidden: false
logger:
   default: error

remote:
  - platform: harmony
    name: Tim's hub
    host: 192.168.178.24

climate:
    platform: nest

fritzbox:
  devices:
    host: 192.168.178.1
    username: !secret fritz_username
    password: !secret fritz_password

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.clock
      - group.all_covers
      - group.all_switches
      - camera.foscam_camera
      - climate.meerzand
      - media_player.sird_14_c3
      - media_player.soundbar

  network:
    name: Network
    view: yes
    entities:
      - group.networkgroup
      - group.fritzbox

  automations:
    name: Automations
    view: yes
    entities:
      - automation.sunscreen_down
      - automation.sunscreen_up

  networkgroup:
    entities:
      - device_tracker.fritzbox
      - device_tracker.switch1
      - device_tracker.Switch2
      - device_tracker.storer
      - device_tracker.holder
      - device_tracker.laserprinter
      - device_tracker.harmonyhub
      - device_tracker.googlehome
      - device_tracker.alexa_woonkamer
      - device_tracker.tvwoonkamer
      - device_tracker.internet_radio
      - device_tracker.wemocorner
      - device_tracker.wemocouch
      - device_tracker.wemocam1
      - device_tracker.woonkamertablet
      - device_tracker.pc19216817863


  woonkamer:
    name: Woonkamer
    entities:
      - media_player.woonkamer
      - sensor.cresta_woonkamer_temperature
      - sensor.cresta_studeerkamer_temperature

  clock:
    name: Date and Time 
    entities:
      - sensor.date__time
      - sensor.cresta_woonkamer_temperature
      - sensor.cresta_studeerkamer_temperature
      - sensor.cresta_slaapkamer_temperature

  Weather:
    name: Weather
    view: yes
    entities:
       - group.wunderground
       - group.buienradar


  buienradar:
    name: Buienradar
    entities:
     - sensor.br_stationname
     - sensor.br_symbol
     - sensor.br_temperature
     - sensor.br_ground_temperature
     - sensor.br_humidity
     - sensor.br_irradiance
     - sensor.br_precipitation
     - sensor.br_precipitation_average
     - sensor.br_precipitation_forecast_average
     - sensor.br_precipitation_forecast_total
     - sensor.br_pressure
     - sensor.br_visibility
     - sensor.br_wind_direction
     - sensor.br_wind_direction_azimuth
     - sensor.br_wind_force
     - sensor.br_wind_gust
     - sensor.br_wind_speed




frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem

# Checks for available updates
updater:

# Enable configuration panel
config:

# Discover some devices automatically
discovery:
  ignore:
    - frontier_silicon

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#customization

# turn on local mqtt broker
#mqtt:
#  broker: localhost
#  port: 1883
#  client_id: homeassistant1
#  keepalive: 60
#  protocol: 3.1


# Location/geofencing etc.
device_tracker:
        # Disabled because fritz platform does not allow me to filter out devices
        #   - platform: fritz
        #username: admin
        #password: !secret adminpasswd
        #track_new_devices: true
        #host: 192.168.178.1
        #interval_seconds: 60
        #consider_home: 0:03:00
   - platform: nmap_tracker
     hosts: 192.168.178.0/24
     home_interval: 5
     track_new_devices: true
     #
     # Exclude certain laptops
     exclude:
       - 192.168.178.83
       - 192.168.178.40
   - platform: unifi_direct
     host: 192.168.178.63
     username: admin
     password: !secret unify_password
     #
     # Use ping platform for known hosts. Make sure mobiles always get the right IP
     #   - platform: ping
     # interval_seconds: 60
     #hosts:
     # - tim: 192.168.178.XXX
     # - saskia: 192.168.178.XXX


rfxtrx:
  device: /dev/ttyUSB0
  debug: True

cover:
  - platform: group
    name: Front Window
    entities:
      - cover.raam_links_voor
      - cover.raam_midden_voor
      - cover.raam_rechts_voor

        #cover:
  - platform: rfxtrx
    automatic_add: False
    devices:
      071a03000d080601:
        name: Raam achter
      071a03000d080602:
        name: Raam zijkant
      071a03000d080603:
        name: Raam Links voor
      071a03000d080604:
        name: Raam Midden voor
      071a03000d080609:
        name: Raam Rechts voor

cast:
  media_player:
    host: 192.168.178.64

media_player:
  - platform: frontier_silicon
    host: 192.168.178.43


light:
  - platform: rfxtrx
    automatic_add: True

switch:
  - platform: rfxtrx
    automatic_add: False
    devices:
      0b110001014206060a010f50:
        name: Voordeur
      0b110002019ac87e01040f50:
        name: Deurbel
        fire_event: True

#  - platform: mqtt
#    name: Lamp 1
#    command_topic: "cmnd/lamp1/power"
#    state_topic: "stat/lamp1/+"
#
weather:
  - platform: buienradar
  - platform: darksky
    api_key: !secret dark_sky_key 

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret


sensor:
# Weather prediction
  - platform: yr
# Time and date
  - platform: time_date
    display_options:
      - date_time
  - platform: rfxtrx
    automatic_add: True
    devices:
      0a5207013b0e00d02d0169:
        name: Cresta woonkamer
      0a5207064e0e01052c0189:
        name: Cresta studeerkamer
      0a520703750e0106310189:
        name: Cresta slaapkamer

  - platform: darksky
    api_key: !secret dark_sky_key
    forecast: 1
    update_interval: 01:00
    monitored_conditions:
      - summary
      - icon
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - wind_speed
      - nearest_storm_distance
      - nearest_storm_bearing

  - platform: buienradar
    timeframe: 30
    monitored_conditions:
      - stationname
      - symbol
      - humidity
      - temperature
      - groundtemperature
      - windspeed
      - windforce
      - winddirection
      - windazimuth
      - pressure
      - visibility
      - windgust
      - precipitation
      - irradiance
      - precipitation_forecast_total
      - precipitation_forecast_average

  - platform: fritzbox_netmonitor
    host: 192.168.178.1
    username: !secret fritz_username
    password: !secret fritz_password

# Living room camera
camera:
  - platform: foscam
    ip: 192.168.178.27
    port: 88
    username: timt
    password: !secret camera_password

notify:
  - platform: pushbullet
    name: Tim
    api_key: !secret pushbullet_key


influxdb:
  host: 127.0.0.1

wemo:
  static:
    - 192.168.178.42
    - 192.168.178.84
    - 192.168.178.37

automation: !include automations.yaml

script: !include scripts.yaml
