homeassistant:
  # Name of the location where Home Assistant is running
  name: Meerzand
  # Location required to calculate the time the sun rises and sets
  latitude: 51.4432618
  longitude: 5.4087704
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 73
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
     script.voordeur_open:
       hidden: True 
     device_tracker.asuswrtn66ufritzbox:
       friendly_name: ASUS WRT-N66U
       icon: mdi:router-wireless
     device_tracker.nexuswoonkamer:
       icon: mdi:tablet-android
     device_tracker.printerlanfritzbox:
       icon: mdi:printer
     sensor.pws_temp_c:
       friendly_name: Buitentemperatuur
     sensor.pws_wind_dir:
       friendly_name: Windrichting
     sensor.pws_wind_kph:
       friendly_name: Windsnelheid
     sensor.pws_alerts:
       friendly_name: Alerts
     sensor.pws_observation_time:
       friendly_name: Laatste meting
     sensor.pws_precip_1hr_metric:
       friendly_name: Regen (1 uur)
     sensor.pws_precip_today_metric:
       friendly_name: Regen vandaag
     sensor.pws_visibility_km:
       friendly_name: Zicht (km)

logger:
   default: error
   logs:
     homeassistant.components.rfxtrx: debug
     
group:
  network:
    name: Network
    entities:
      - device_tracker.asuswrtn66ufritzbox
      - device_tracker.nexuswoonkamer
      - device_tracker.printerlanfritzbox
      - device_tracker.roamerfritzbox
      - device_tracker.switch2
  woonkamer:
    name: Woonkamer
    entities:
      - media_player.woonkamer
      - sensor.cresta_woonkamer_temperature

  clock:
    name: Date and Time
    entities:
      - sensor.date__time

  environment:
    name: Environment
    entities:
     - sensor.pws_location
     - sun.sun
     - sensor.yr_symbol
     - sensor.pws_alerts
     - sensor.pws_observation_time
     - sensor.pws_precip_1hr_metric
     - sensor.pws_precip_today_metric
     - sensor.pws_temp_c
     - sensor.pws_visibility_km
     - sensor.pws_wind_dir
     - sensor.pws_wind_kph
   

frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#customization

# turn on local mqtt broker
mqtt:
  broker: localhost
  port: 1883
  client_id: homeassistant1
  keepalive: 60
  protocol: 3.1


# Location/geofencing etc.
device_tracker:
   - platform: nmap_tracker
     hosts: 192.168.178.1/24
   - platform: owntracks
     max_gps_accuracy: 200
     waypoints: True
       
rfxtrx:
  device: /dev/ttyUSB0
  debug: True

cover:
  platform: rfxtrx
  automatic_add: True
  devices:
    071a03000d080601: 
      name: Raam achter
    071a03000d080602:
      name: Raam zijkant
    071a03000d080603:
      name: Raam Links voor
    071a03000d080604:
      name: Raam Midden voor
    071a03000d080609:
      name: Raam Rechts voor

media_player:
  - platform: cast

light:
  - platform: rfxtrx
    automatic_add: True

switch:
  - platform: rfxtrx
    automatic_add: True
    devices:
      0b110001014206060a010f50:
        name: Voordeur

 

sensor:
# Weather prediction
  - platform: yr
# Time and date
  - platform: time_date
    display_options:
      - date_time
  - platform: rfxtrx
    automatic_add: True
    devices:
      0a5207013b0e00d02d0169:
        name: Cresta woonkamer

  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - station_id
      - alerts
      - observation_time
      - precip_1hr_metric
      - precip_today_metric
      - temp_c
      - visibility_km
      - wind_dir
      - wind_kph
# Living room camera
camera:
  - platform: foscam
    ip: 192.168.178.57
    port: 88
    username: timt
    password: !secret camera_password

notify:
  - platform: pushbullet
    name: Tim
    api_key: !secret pushbullet_key

automation:
  - alias: 'warn when door opens'
    initial_state: True
    hide_entity: True
    trigger: 
      platform: state
      entity_id: switch.voordeur
      from: 'off'
      to: 'on'
    action: 
      service: notify.Tim
      data:
        message: "Door open"
        title: "Door open"
  - alias: "voordeur nog open"
    hide_entity: True
    trigger:
      platform: state
      entity_id: switch.voordeur
      from: 'off'
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.voordeur_open
  - alias: 'voordeur dicht'
    hide_entity: True
    trigger:
      platform: state
      entity_id: switch.voordeur
      from: 'on'
      to: 'off'
    action: 
      service: homeassistant.turn_off
      entity_id: script.voordeur_open

script:
  voordeur_open:
    alias: 'voordeur staat open'
    sequence:
      - delay:
          minutes: 5
      - service: notify.Tim
        data:
          message: 'De voordeur staat nog open'
          title: 'Warning front door open'

